spring:
  application:
    name: mc-dialog

  jpa:
    generate-ddl: false
    open-in-view: true
  datasource:
    url: jdbc:postgresql://postgres_db/mc_dialog
    username: postgres
    password: postgres

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

server:
  port: 8088

app:
  jwt:
    secret: "53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855"

  kafka:
    bootstrap-servers: 79.174.80.200:9092
    kafkaMessageNotificationTopic: "notification-topic"

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://mc-eureka-conteiner:8888/eureka/
  instance:
    hostname: localhost
