spring:
  application:
    name: "mc-storage"

cloud:
  yandex:
    s3:
      bucket-name: skb44gr
      access-key: YCAJEOK5hcucGv_JMFnDRdfba
      secret-key: YCMnZVHVigHbHcMqCO4LopqQO-gacdaolsIS6mxn
      endpoint-url: https://storage.yandexcloud.net

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://mc-eureka-conteiner:8888/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost