server:
  port: 8086

spring:
  application:
    name: mc-auth

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    drop-first: false

  datasource:
    url: jdbc:postgresql://postgres_db/mc_auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  kafka:
    bootstrap-servers: 79.174.80.200:9092
    kafkaMessageGroupId: auth_consumer

token:
  signing:
    key: "53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855"
    refreshTokenExpiration: 5m

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone:  http://mc-eureka-conteiner:8888/eureka/
  instance:
    hostname: localhost